apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mongodb","namespace":"workshop"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mongodb"}},"serviceName":"mongodb-svc","template":{"metadata":{"annotations":{"prometheus.io/scrape":"false"},"labels":{"app":"mongodb"}},"spec":{"containers":[{"env":[{"name":"MONGO_INITDB_ROOT_USERNAME","valueFrom":{"secretKeyRef":{"key":"MONGO_USERNAME","name":"mongodb-secret"}}},{"name":"MONGO_INITDB_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"MONGO_PASSWORD","name":"mongodb-secret"}}},{"name":"MONGO_INITDB_DATABASE","valueFrom":{"secretKeyRef":{"key":"MONGO_DATABASE","name":"mongodb-secret"}}}],"image":"mongo:6.0","livenessProbe":{"exec":{"command":["sh","-c","mongosh -u \"$MONGO_INITDB_ROOT_USERNAME\" -p \"$MONGO_INITDB_ROOT_PASSWORD\" --eval \"db.adminCommand('ping')\" --quiet\n"]},"failureThreshold":3,"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"name":"mongodb","ports":[{"containerPort":27017}],"readinessProbe":{"exec":{"command":["sh","-c","mongosh -u \"$MONGO_INITDB_ROOT_USERNAME\" -p \"$MONGO_INITDB_ROOT_PASSWORD\" --eval \"db.adminCommand('ping')\" --quiet\n"]},"failureThreshold":3,"initialDelaySeconds":5,"periodSeconds":5,"timeoutSeconds":5},"resources":{"limits":{"cpu":"300m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"runAsNonRoot":true,"runAsUser":999},"volumeMounts":[{"mountPath":"/data/db","name":"mongo-data"}]}],"securityContext":{"fsGroup":999,"fsGroupChangePolicy":"OnRootMismatch"},"terminationGracePeriodSeconds":60}},"volumeClaimTemplates":[{"metadata":{"name":"mongo-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"gp3","volumeMode":"Filesystem"}}]}}
  creationTimestamp: "2026-03-17T13:48:35Z"
  generation: 2
  name: mongodb
  namespace: workshop
  resourceVersion: "93213"
  uid: db3812c8-a0bf-4671-99cc-0b6ede85b1a1
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-svc
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGO_USERNAME
              name: mongodb-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_PASSWORD
              name: mongodb-secret
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              key: MONGO_DATABASE
              name: mongodb-secret
        image: mongo:6.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --eval "db.adminCommand('ping')" --quiet
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --eval "db.adminCommand('ping')" --quiet
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 999
        terminationMessagePath: /stage/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
      terminationGracePeriodSeconds: 60
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: gp3
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mongodb-7c48f97647
  observedGeneration: 2
  replicas: 1
  updateRevision: mongodb-b574479c9
